### ISSUE TITLE
Speed up python module with fewer indexing calls.

### ISSUE THREAD

**Issue by bmschmidt** [oldweather/IMMA#2]
I find I can get the python code to go a little over 2x faster by stripping out self-assignments in the class method.

```python
        for i in range(len(parameters)):
              if ( definitions[parameters[i]][0] != None ):
                 self[parameters[i]] = as_string[Position:Position+definitions[parameters[i]][0]]
```
becomes
```python
        for parameter in parameters:
            if ( definitions[parameter][0] != None ):
                value = as_string[Position:Position+definitions[parameter][0]]
                 .... (other stuff done to value)
                self[parameters] = value 
```

I'd bundle a pull request but I've already changed some other portions of the code for my own purposes and I'm not sure if anyone is using this module, anyway.

**Comment by philip-brohan** [comment]
You are not the only user, but it's a pretty elite group. (I thought you'd be using the R interface).

Thanks for the suggestion, if it works for me I will certainly adopt it.

I moved development of the Python IMMA library into it's own repository - http://brohan.org/pyIMMA/ - no promises about speed (not looked), but that version does support most of IMMA1.

If you are using ICOADS IMMA data, have you considered using the netCDF version - https://data.nodc.noaa.gov/cgi-bin/iso?id=gov.noaa.nodc:ICOADS-netCDF

**Comment by philip-brohan** [comment]
Speed increase checks out - I don't get a factor of 2, but the effect is large and it's the sort of thing that might be quite dependent on the python implementation.

Also, your version is just better - code shorted and clearer.

So, duly implemented, thank you. (Uploaded to GitHub as of 2018-10-05:13:25 UTC - this code does not have so many users that I'm going to do formal releases).

**Comment by bmschmidt** [comment]
Great, thanks! I'll file any new issues over there.

I'm working with these as geoJSON now, and I find python easier to use for that.
